language: php

php:
  - 5.5
  - 5.4
  - hhvm

env:
  - SYMFONY_VERSION=v2.0.7
# - SYMFONY_VERSION=origin/2.0
# - SYMFONY_VERSION=origin/master

script: phpunit

notifications:
  email:
    - isc.suriyaa@gmail.com
